root = "."
tmp_dir = "tmp"

[build]
  cmd =  "go build -o ./tmp/main ./cmd"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_file = []
  log = "air.log"
  stop_on_error = true
  send_interrupt = false
  kill_delay = 500
  poll = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true